### ISSUE TITLE
終了ステータスがエラーになる

### ISSUE THREAD

**Issue by aita** [shiguredo/ayame#2]
`log.Fatal` は内部で `os.Exit(1)` を呼ぶので常に終了ステータスがエラーになっています

https://github.com/shiguredo/ayame/blob/develop/main.go#L22

**Comment by kdxu** [comment]
ありがとうございます！
`log.Print` にすることで対応しました。 https://github.com/shiguredo/ayame/commit/61f7e60c08ee15240283aad8345f8963ae31cadd

**Comment by aita** [comment]
修正していただいて大変申し訳ないのですが、ListenAndServeはドキュメントで常に `non-nil error` を返す
とドキュメントで言及されているので、元のコードの `log.Fatal`の呼び出しで問題なく、わたしの誤解のでした。

https://golang.org/pkg/net/http/#ListenAndServe
> ListenAndServe always returns a non-nil error.

**Comment by kdxu** [comment]
了解です。ありがとうございます。では revert して対応いたします！

**Comment by kdxu** [comment]
revert して対応いたしました。https://github.com/shiguredo/ayame/commit/c7e650cf4c70db1e7cb48b80320cc3785b9c1ca8
ありがとうございました。
